routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home')->name('home');

Auth::routes(['verify' => true]);

Route::get('/corporates', 'OrderController@corporateShow')->name('corporates.create');

Route::post('/corporates/request', 'OrderController@saveQuoteRequest')->name('corporates.store');

Route::group(['middleware' => ['verified', 'auth']], function () {

    Route::get('/dash', 'HomeController@index')->name('dash');
    
    Route::post('/user/wishlist', 'WishlistController@store')->name('wishlist.store');

    Route::post('/user/profile/update', 'UserController@update')->name('user.profile.update');

    Route::post('user/profile/changePassword', 'UserController@changePassword')->name('user.profile.changePassword');


    Route::get('/user/orders/{order}', 'OrderController@show')->name('orders.show');

    Route::get('/orders/checkout', 'OrderController@checkout')->name('checkout');

    Route::post('/orders/confirm', 'OrderController@confirm')->name('orders.confirm');

    Route::get('/orders/confirmed', 'OrderController@confirmed')->name('orders.confirmed');

    Route::post('/orders/{order}/cancel', 'OrderController@cancel')->name('orders.cancel');

    Route::post('/wishlist/{book}/delete', 'WishlistController@delete')->name('wishlist.delete');

    Route::post('/reviews', 'ReviewController@store')->name('reviews.store');

    Route::group(['prefix' => '/admin', 'middleware' => ['role:admin']], function () {
        Route::get('/dash', 'AdminController@welcome')->name('admins.welcome');
        
        Route::get('/dash/users', 'AdminController@users')->name('admins.users');
        Route::get('/dash/users/{user}', 'AdminController@userProfile')->name('admins.user_profile');        
        Route::get('/dash/orders', 'AdminController@orders')->name('admins.orders');
        Route::get('/dash/orders/{order}', 'AdminController@showOrder')->name('admins.orders.show');

        Route::post('/dash/orders/change_status', 'AdminController@changeOrderStatus')->name('admins.orders.change_status');

        Route::get('/creator', 'AdminController@creator')->name('admins.creator');

        Route::post('/creator/save/author', 'AdminController@saveAuthor')->name('admins.creator.author.save');

        Route::post('/creator/save/category', 'AdminController@saveCategory')->name('admins.creator.category.save');

        Route::post('/creator/save/publisher', 'AdminController@savePublisher')->name('admins.creator.publisher.save');

        Route::post('/creator/save/book', 'AdminController@saveBook')->name('admins.creator.book.save');

        Route::get('/vendors', 'DeliveryVendorController@index')->name('admins.deliveryvendor.index');

        Route::post('/vendors', 'DeliveryVendorController@store')->name('admins.deliveryvendor.store');

        Route::post('/vendors/{vendor}/delete', 'DeliveryVendorController@delete')->name('admins.deliveryvendor.delete');

        Route::post('/vendors/assign/order', 'DeliveryVendorController@assign')->name('admins.deliveryvendor.assign');        

        
        Route::post('/creator/stock/get', 'AdminController@getStock')->name('admins.stock.get');
        Route::post('/creator/stock/update', 'AdminController@updateStock')->name('admins.stock.update');

        Route::group(['middleware' => ['role:super-admin']], function () {

            Route::post('/users/{user}/attachrole', 'AdminController@attachRole')->name('admins.attach.role');
            Route::post('/users/{user}/detachrole', 'AdminController@detachRole')->name('admins.detach.role');


            Route::get('/uploads', 'AdminController@uploads')->name('uploads.create');
            Route::post('/uploads/book', 'AdminController@saveBookFile')->name('uploads.book');
            Route::post('/uploads/{upload}/process', 'AdminController@processFile')->name('uploads.process');
            Route::post('/uploads/{upload}/delete', 'AdminController@deleteFile')->name('uploads.delete');

            Route::post('/uploads/author', 'AdminController@saveAuthorFile')->name('uploads.author');

            Route::post('/uploads/publisher', 'AdminController@savePublisherFile')->name('uploads.publisher');

            Route::post('/uploads/category', 'AdminController@saveCategoryFile')->name('uploads.category');

        });

    });


});

Route::get('/cart', 'CartController@show')->name('carts.show');

Route::post('/cart/{book}/delete', 'CartController@delete')->name('carts.delete');

Route::post('/cart/delete', 'CartController@deleteAll')->name('carts.delete_all');

Route::get('/categories', 'CategoryController@index')->name('categories.index');

Route::get('/authors', 'AuthorController@index')->name('authors.index');

Route::get('/publishers', 'PublisherController@index')->name('publishers.index');

Route::get('/books/{book}', 'BookController@show')->name('books.show');

Route::get('/authors/{author}', 'AuthorController@show')->name('authors.show');

Route::get('/categories/{category}', 'CategoryController@show')->name('categories.show');

Route::get('/publishers/{publisher}', 'PublisherController@show')->name('publishers.show');



Route::post('/user/cart/add', 'CartController@store');

Route::get('/about', 'HomeController@about')->name('about');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/privacy-policy', 'HomeController@privacy')->name('privacy');
Route::get('/shopping-guideline', 'HomeController@guideline')->name('guideline');
Route::get('/terms-conditions', 'HomeController@terms')->name('terms');
Route::get( '/return-policy', 'HomeController@returnPolicy')->name( 'return_policy');
Route::post('/contact', 'HomeController@storeContact')->name('contacts.store');


Route::get('/redirect/{provider}/auth', 'Auth\SocialLoginController@redirectToProvider')->name('social.login');
Route::get('/callback/{provider}/auth', 'Auth\SocialLoginController@handleProviderCallback');

app/Order.php
<?php

namespace App;

use App\User;
use App\Model;
use App\OrderDetail;
use App\Transaction;
use App\DeliveryVendor;

class Order extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }


    public function orderDetails()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function transaction()
    {
        return $this->hasOne(Transaction::class);
    }

    public function deliveryVendor()
    {
        return $this->belongsTo(DeliveryVendor::class, 'delivery_vendor_id', 'id');
    }

    public function getTotalPriceAttribute()
    {
        return $this->orderDetails()->sum('price');
    }

    public function getStatusBadgeAttribute()
    {
        switch ($this->status) {
            case 'Approved':
                return 'info';
                break;

            case 'Cancelled':
                return 'danger';
                break;

            case 'Delivered':
                return 'success';
                break;

            default:
                return 'warning';
                break;

        }

    }


    public function scopeToday($query)
    {
        return $query->whereDate('created_at', date('Y-m-d'));
    }



    public static function saveNewOrder($request, $address, $user)
    {
        $order = new Order;
        $order->delivery_date = date('Y-m-d', strtotime('+3days'));
        $order->address = $request->address . ', ' . $address['sub_district']['name'];
        $order->district = $address['district']['name'];
        $order->name = $request->fname . ' ' . $request->sname;
        $order->phone = $request->phone;
        $order->reference = $request->reference;
        $order->is_gift =$request->_b_g;
        $order->shipping_charge = intval(env('SHIPPING_CHARGE'));
        return $user->orders()->save($order);
    } 

    public function getOrderActionAttribute()
    {
        switch ($this->status) {
            case 'Approved':
            case 'Pending':
                return 'Cancel';
                    break;

            case 'Cancelled':
            case 'Delivered':
                return 'N/A';
                break;

            default:
                return 'N/A';
                break;
        }
    }


    public function getIsUserNeedActionButtonAttribute()
    {
        return preg_match('/(pending|approved)/i', $this->status);
    }

}

resources/views/admins/dash.blade.php
@extends('admin_layouts.master')

@section('main-content')

<section class="content">

    <div class="row">

        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3> {{ $users['today'] }} </h3>

                    <p>Todays Users</p>
                </div>
                <div class="icon">
                    <i class="fa fa-users"></i>
                </div>
                <a href=" {{ route('admins.users', ['_segment' => 'today']) }} " class="small-box-footer">
                    More info <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>


        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3> {{ $users['total'] }} </h3>

                    <p>Total Users</p>
                </div>
                <div class="icon">
                    <i class="fa fa-users"></i>
                </div>
                <a href=" {{ route('admins.users', ['_segment' => 'total']) }} " class="small-box-footer">
                    More info <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>



        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3> {{ $orders['today'] }} </h3>

                    <p>Todays Orders</p>
                </div>
                <div class="icon">
                    <i class="fa fa-shopping-cart"></i>
                </div>
                <a href=" {{ route('admins.orders', ['_segment' => 'today']) }} " class="small-box-footer">
                    More info <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>

        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3> {{ $orders['total'] }} </h3>

                    <p>Total Orders</p>
                </div>
                <div class="icon">
                    <i class="fa fa-shopping-cart"></i>
                </div>
                <a href=" {{ route('admins.orders', ['_segment' => 'total']) }} " class="small-box-footer">
                    More info <i class="fa fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>

    </div>

</section>


@endsection

resources/views/admins/order_details.blade.php
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Boibhandar | {{ $headline }}</title>


</head>

<body>
    <div class="invoice-box" style="max-width: 800px;
        margin: auto;
        padding: 30px;
        border: 1px solid #eee;
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;">

        <div style="min-height: 40px;
            border: 2px solid #000;
            color: #000;
            text-align: center;
            border-radius: 4px;">
            <h2 style="letter-spacing: 2px;">Invoice</h2>
        </div>



        <table cellpadding="0" cellspacing="0" style="width: 100%; line-height: inherit; text-align: left;">
            <tr class="top">
                <td colspan="3" style="padding: 5px; vertical-align: top;">
                    <table style="width: 100%; line-height: inherit; text-align: left;">
                        <tr>
                            <td class="title" style="padding: 5px; vertical-align: top; font-size: 14px;">
                                <img src="\images\logo.svg" style="width:100%; max-width:180px; cursor:pointer;" onclick="window.location='/'">
                                <ul style="list-style: none; padding-left:0;">
                                    <li><span
                                            style="background-color: #e5e5e5; padding: 5px 10px 5px 10px; border-radius: 4px;"><strong>Invoice
                                                #: {{ 'BOID' . $order->id }} </strong></span></li>
                                    <li style="margin-top: 7px;"><strong> Ordered on: </strong><span>
                                            {{ date('M d, Y', strtotime($order->created_at)) }} </span></li>
                                    <li><strong>User:</strong><span> {{ $order->user->fullName }} </span></li>
                                    <li><strong>Recipient:</strong><span> {{ $order->name }} </span></li>
                                    <li><strong>Phone:</strong><span> {{ $order->phone }} </span></li>
                                    <li><strong>Address:</strong><span> {{ $order->address . ' ' . $order->district }}
                                        </span></li>
                                    <li><strong>Payment method:</strong><span>
                                            {{ strtoupper($order->transaction->pay_type) }} </span></li>
                                </ul>
                            </td>


                            <td style="padding: 5px; vertical-align: top; text-align: right;">

                            </td>
                        </tr>
                    </table>
                </td>
            </tr>



            <tr class="heading" style="color: #000; font-size:14px; border: 1px solid #000;">
                <td
                    style="border: 1px solid #000; padding: 5px; padding-left: 10px; vertical-align: top;  font-weight: bold; border-top-left-radius: 4px; border-bottom-left-radius: 4px;">
                    Item
                </td>

                <td
                    style="border: 1px solid #000; padding: 5px; vertical-align: top;  font-weight: bold; text-align: center;">
                    Quantity
                </td>

                <td
                    style="border:1px solid #000; padding: 5px; padding-right: 10px; vertical-align: top;  font-weight: bold; text-align: right; border-top-right-radius: 4px; border-bottom-right-radius: 4px;">
                    Price
                </td>
            </tr>

            @foreach ($order->orderDetails as $detail)
            @php($authors = $detail->book->authorList() )
            <tr style="font-size:12px;">
                <td style="padding: 5px; padding-left: 10px;">
                    {!! '<strong>' . $detail->book->title . '</strong> (' . implode(', ', $authors) . ')' !!}
                </td>

                <td style="padding: 5px; text-align: center;">
                    {{ $detail->quantity }}
                </td>

                <td style="padding: 5px; text-align: right; padding-right: 10px;">
                    {{ $detail->total_price }}
                </td>
            </tr>

            @endforeach

            <tr class="total" style="font-size:12px;">
                <td style="padding: 5px;"></td>
                <td style="padding: 5px;"></td>

                <td style="padding: 5px; text-align: right; border-top: 2px solid #eee; padding-right: 10px;">
                    Subtotal: {{ $total }}
                </td>
            </tr>

            @if($order->is_gift)
                <tr style="font-size:12px;">
                    <td style="padding: 5px;"></td>
                    <td style="padding: 5px;"></td>

                    <td style="padding: 5px; text-align: right; padding-right: 10px;">
                        Gift Wrap: {{ $gift }}
                    </td>

                </tr>
            @endif

            <tr style="font-size:12px;">
                <td style="padding: 5px;"></td>
                <td style="padding: 5px;"></td>

                <td style="padding: 5px; text-align: right; padding-right: 10px;">
                    Shipping: {{ $order->shipping_charge }}
                </td>
            </tr>


            <tr class="total">
                <td style="padding: 5px;"></td>
                <td style="padding: 5px;"></td>

                <td
                    style="padding: 5px; text-align: right; background-color: #e7e7e7; border-radius: 4px; font-weight: bold; padding-right: 10px;">
                    Total: {{ $total + $gift + $order->shipping_charge }}
                </td>
            </tr>

            <tr>
                <td colspan="3" style="padding-top: 20px">
                    <hr>
                </td>
            </tr>


            <tr>
                <td colspan="3" style="text-align:center; margin-top: 0px;">
                    <span> www.boibhandar.com |</span>
                    <span> support@boibhandar.com |</span>
                    <span> <img src="\images\fb.png" style="width: 12px"><img src="\images\insta.png"
                            style="width: 12px; padding-left: 5px; padding-right: 5px;">/ boibhandar</span>
                </td>
            </tr>


            {{-- <tr class="information">
                <td colspan="3" style="padding: 5px; vertical-align: top;">
                    <table style="width: 100%; line-height: inherit; text-align: left;">
                        <tr>
                            <td style="padding: 5px; vertical-align: top; padding-bottom: 40px;">
                             <ul style="list-style: none; padding-left: 0;">
                                	<li>Boibhandar Ltd.</li>
                                	<li>WASA Circle, Chattogram</li>
                                	<li>Chattogram-4203, Bangladesh</li>
                                </ul>
                            </td>
                            
                            <td style="padding: 5px; vertical-align: top; padding-bottom: 40px; text-align: right;">

                                	<li>www.boibhandar.com</li>
                                	<li>support@boibhandar.com</li>
                                	<li><img src="\images\fb.png" style="width: 12px"><img src="\images\insta.png" style="width: 12px; padding-left: 5px; padding-right: 5px;">/ boibhandar</li>

                            </td>
                        </tr>
                    </table>
                </td>
            </tr> --}}


        </table>

        <div style="text-align: center;">
            <h4 style="margin-top:8px; margin-bottom:0px; letter-spacing: 1px;">Thank you for shopping with us :)</h4>
        </div>

    </div>
</body>

</html>

resources/views/admins/order_list_box_body.blade.php
<div class="box-body">
    <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row">
            {{-- <div class="col-sm-6">
                                <div class="dataTables_length" id="example1_length"><label>Show <select
                                            name="example1_length" aria-controls="example1"
                                            class="form-control input-sm">
                                            <option value="10">10</option>
                                            <option value="25">25</option>
                                            <option value="50">50</option>
                                            <option value="100">100</option>
                                        </select> entries</label></div>
                            </div> --}}

            <div class="col-sm-6">
                <div id="example1_filter" class="dataTables_filter"><label>Search: <input type="search"
                            class="form-control input-sm" placeholder="" aria-controls="example1"></label></div>
            </div>

        </div>

        <div class="row">
            <div class="col-sm-12">

                @if (count($orders) > 0)
                    <table id="example1" class="table table-bordered table-striped dataTable" role="grid"
                        aria-describedby="example1_info">
                        <thead>
                            <tr role="row">
                                <th>#</th>
                                <th>ID</th>
                                <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="Browser: activate to sort column ascending" aria-sort="descending">Customer
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="Rendering engine: activate to sort column ascending">Recipient
                                </th>
                                <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="Browser: activate to sort column ascending" aria-sort="descending">Phone
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="Platform(s): activate to sort column ascending">
                                    Gift</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="Platform(s): activate to sort column ascending">
                                    Payment</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="Engine version: activate to sort column ascending">Status</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="CSS grade: activate to sort column ascending">Ref.</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="CSS grade: activate to sort column ascending">Ordered On</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="CSS grade: activate to sort column ascending">Total</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="CSS grade: activate to sort column ascending">Action</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                    aria-label="CSS grade: activate to sort column ascending">Shipper</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($orders as $order)

                            <tr role="row" class=" {{ $loop->iteration&1 ? 'odd' : 'even'}} ">
                                <td> {{ $loop->iteration }}</td>
                                <td> <a href="{{ route('admins.orders.show', $order->id) }}">{{ 'BOID' . $order->id }}</a></td>
                                <td class=""> <a href="{{ route ('admins.user_profile', $order->user->id) }}"> {{ $order->user->fname }} </a> </td>
                                <td class="sorting_1"> {{ explode(" ", $order->name)[0] }} </td>
                                <td> {{ $order->phone }} </td>
                                <td> {{ $order->is_gift ? 'Yes' : 'No' }} </td>
                                <td> {{ $order->transaction->pay_type }} </td>
                                <td> <span class="label label-{{ $order->statusBadge }}">{{ ucwords($order->status) }}</span></td>
                                <td> {{ $order->reference }} </td>
                                <td> {{ date('M d, Y', strtotime($order->created_at)) }} </td>
                                <td> {{ $order->transaction->total_price }} </td>
                                <td> 
                                    @php($status = strtolower($order->status))
                                    @if($status == 'pending')
                                        
                                        <span><button onclick="change_order_status({{ $order->id }}, 'Approved')" class="btn btn-sm btn-primary">Approve</button></span> <span><button onclick="change_order_status({{ $order->id }}, 'Cancelled')" class="btn btn-sm btn-danger">Cancel</button></span>
                                        
                                    @elseif($status == 'cancelled')
                                    
                                        <span><button onclick="change_order_status({{ $order->id }}, 'Pending')" class="btn btn-sm btn-primary">Pending</button></span>
                                    
                                    @elseif($status == 'approved')
                                    
                                        <span><button onclick="change_order_status({{ $order->id }}, 'Delivered')" class="btn btn-sm btn-success">Delivered</button></span> <span><button onclick="change_order_status({{ $order->id }}, 'Cancelled')" class="btn btn-sm btn-danger">Cancel</button></span>
                                    
                                    @else
                                        <span>N/A</span>
                                    @endif

                                </td>

                                <td>
                                    @if ($status != 'cancelled')
                                        <span>{{ $order->deliveryVendor != null ? $order->deliveryVendor->name : 'N/A' }}</span>                                        
                                    @else
                                        <span>N/A</span>
                                    @endif
                                    @if($status != 'cancelled' && $status != 'delivered')
                                        <span><button type="button" data-toggle="modal" data-target="#vendorAssignModal" class="btn btn-sm btn-danger" onclick="setOrderIdToAssignDeliveryVendor('{{ $order->id }}')">Assign</button></span>
                                    @endif

                                </td>
                            </tr>

                            @endforeach


                        </tbody>



                    </table>
                    
                @else
                    <h4 class="text-center" style="color:red;">No order was found!</h4>                    
                @endif


            </div>
        </div>


        <div class="row">
            {{-- <div class="col-sm-5">
                                <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing
                                    1 to 10 of 57 entries</div>
                            </div> --}}

            <div class="col-sm-7">


                {{-- <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous disabled" id="example1_previous"><a href="#"
                                                aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a></li>
                                        <li class="paginate_button active"><a href="#" aria-controls="example1"
                                                data-dt-idx="1" tabindex="0">1</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1"
                                                data-dt-idx="2" tabindex="0">2</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1"
                                                data-dt-idx="3" tabindex="0">3</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1"
                                                data-dt-idx="4" tabindex="0">4</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1"
                                                data-dt-idx="5" tabindex="0">5</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1"
                                                data-dt-idx="6" tabindex="0">6</a></li>
                                        <li class="paginate_button next" id="example1_next"><a href="#"
                                                aria-controls="example1" data-dt-idx="7" tabindex="0">Next</a></li>
                                    </ul>
                                </div> --}}
            </div>

        </div>


    </div>
</div>